--SELECCIONA A TODOS LOS USUARIOS DE LA TABLA Y LOS ORDENA POR LA EDAD "AGE" DE MENOR A MAYOR
SELECT * FROM users ORDER BY age

-- ESTA ORDENANDO DE MANERA DESENDENTE 
SELECT * FROM users ORDER BY age DESC; 

--ESTE ORDENA DE MANERA ASCENDENTE, PERO POR PREDETERMINADO YA LO ORDENA ASI 
SELECT * FROM users ORDER BY age ASC;


SELECT * FROM users WHERE email = 'ringele@gmail.com' ORDER BY age DESC;

SELECT * FROM users WHERE email = 'ringele@gmail.com' ORDER BY age DESC;